apps/web/app/about/page.tsx, apps/web/app/layout.tsx, apps/web/app/page.tsx, apps/web/app/partners/page.tsx, apps/web/components/core/layout/Content.tsx, apps/web/components/core/layout/Footer.tsx, apps/web/components/core/layout/Header.tsx, apps/web/components/core/layout/Layout.tsx, apps/web/package.json, apps/web/postcss.config.js, apps/web/tailwind.config.js, packages/configs/package.json, packages/configs/tailwind/postcss.config.js, packages/configs/tailwind/tailwind.config.js, packages/ui/Header.tsx, packages/ui/postcss.config.js, packages/ui/styles.css, packages/ui/tailwind.config.js, yarn.lock
Base layout for web app and tailwind css for styles
=> feat: FE-20 | Base Layout and Tailwind

apps/landing-onco/app/api/useContact.ts, apps/landing-onco/app/components/contact/ContactForm.tsx, apps/landing-onco/app/components/shared/button/LandingButton.tsx, apps/landing-onco/package.json, packages/rest/src/utils.ts, packages/tsconfig/base.json, yarn.lock
Please include a summary of your changes.
Please include a list with the tickets involved in this pull request.
- [FE-68](https://trialtech.atlassian.net/browse/FE-68)
=> Add monday

apps/landing-onco/public/locales/en/translation.json
Please include a summary of your changes.
Please include a list with the tickets involved in this pull request.
- [FE-### | Title]([link])
=> type title

.github/pull_request_template.md
Update PR template to fill the needs for this project
- [FE-102 | Update PR template](https://trialtech.atlassian.net/browse/FE-102)
=> FE-102 | Update PR template

package.json, yarn.lock
Add husky dependency to root package.json
- [FE-44 | Git hooks](https://trialtech.atlassian.net/browse/FE-44)
=> FE-44 | Add husky dependency

.husky/_/husky.sh, .vercelignore, apps/web/.env.development, apps/web/.env.production, apps/web/app/[lang]/page.tsx, apps/web/package.json, packages/eslint-config-custom/index.js, packages/ui/core/tabs/Tabs.types.ts, turbo.json, yarn.lock
- Set up project environments for `web`
- Fix for function definition in prettier
- [FE-104 | Environment variables](https://trialtech.atlassian.net/browse/FE-104)
=> FE-104 | Environments

.gitignore
Fix gitignore
- [FE-112 | Add vscode settings to gitignore](https://trialtech.atlassian.net/browse/FE-112)
=> FE-112 | Fix gitignore

apps/web/components/core/layout/footer/Footer.tsx
Remove client code from Footer
- [FE-115 | Review footer layout](https://trialtech.atlassian.net/browse/FE-115)
=> FE-115 | Convert Footer to Server component

apps/landing-onco/components/contact/Contact.tsx, apps/landing-onco/components/contact/ContactForm.tsx, apps/landing-onco/components/cover/Cover.tsx, apps/landing-onco/components/resources/Resources.tsx, apps/landing-onco/components/shared/Footer.tsx, apps/landing/components/clinical-search/ClinicalSearch.tsx, apps/landing/components/contact/Contact.tsx, apps/landing/components/contact/ContactForm.tsx, apps/landing/components/cover/Cover.tsx, apps/landing/components/innovation/Innovation.tsx, apps/landing/components/innovation/components/EDiary.tsx, apps/landing/components/innovation/components/ManagementPortal.tsx, apps/landing/components/innovation/components/UnEnsayoParaMi.tsx, apps/landing/components/innovation/components/UnEnsayoParaMiOnco.tsx, apps/landing/components/medic-network/MedicNetwork.tsx, apps/landing/components/proposal/Proposal.tsx, apps/landing/components/proposal/components/Culture.tsx, apps/landing/components/resources/components/Resources.tsx, apps/landing/components/resources/components/ResourcesContainer.tsx, apps/landing/components/shared/counter/CounterWrapper.tsx, apps/landing/components/shared/footer/Footer.tsx, apps/landing/components/sites/components/Sites.tsx, apps/landing/components/sites/hooks/useSites.ts, apps/landing/components/sponsors/Sponsors.tsx, apps/landing/components/success-cases/SuccessCases.tsx, apps/landing/components/success-cases/components/CasesContainer.tsx, apps/landing/hooks/useMenu.ts, packages/ui/landing/components/SwitchLanguage.tsx
Fix landings build. For some reason Typescript wasn't compiling successfully when using LanguageContext
- [FE-121 | Fix LanguageContext build](https://trialtech.atlassian.net/browse/FE-121)
=> FE-121 | Fix landings build

apps/web/app/[lang]/blog/article/[slug]/components/ArticleTitle.tsx, apps/web/components/shared/blogItem/BlogItem.tsx, apps/web/components/shared/blogItem/BlogItemContent.tsx, apps/web/intl/locales/en.json, apps/web/intl/locales/es.json, apps/web/intl/locales/pt.json, apps/web/package.json, packages/ui/components/dateMask/DateMask.tsx, packages/ui/components/dateMask/DateMask.types.ts, packages/ui/components/dateMask/index.ts, packages/ui/components/index.ts, packages/ui/package.json, yarn.lock
New UI component to format dates
- [FE-133 | Date Mask UI component](https://trialtech.atlassian.net/browse/FE-133)
=> FE-133 | DateMask

apps/web/app/[lang]/blog/article/[slug]/components/ArticleOfInterest.tsx
use BlogItem component instead of custom code for ArticleOfInterest component
- [FE-127 | ArticleOfInterest component]([https://trialtech.atlassian.net/browse/FE-127])
=> use BlogItem component

apps/web/.env.development, apps/web/.env.production, apps/web/intl/components/SwitchLocale.tsx, packages/ui/core/select/Select.tsx, packages/ui/core/select/Select.types.ts
Add new property menuPlacement in Select component, which has two options (top, bottom) that indicates where is Select menu options placed.
This new property should have bottom as default option.
SwitchLocale component should set menuPlacement propety as top
- [FE-134 | Show language selector panel above]([https://trialtech.atlassian.net/browse/FE-134])
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] Web
- [ x ] I have performed a self-review of my own code :innocent:
- [ x ] My code is clean and it follows the guidelines of this project :nail_care:
- [ x ] My changes don't generate new warnings :ok_hand:
=> Feature/FE-134 -  show language selector panel above

packages/ui/package.json
Paginations numbers are not being displayed in /blog/:category
- [FE-136 | Pagination numbers are broken in blog]([https://trialtech.atlassian.net/browse/FE-136])
=> Downgrade React-paginate library

apps/web/components/shared/trendingTopics/TrendingTopics.tsx, apps/web/components/shared/trendingTopics/TrendingTopics.types.ts
Trending Topics component now supports 'orientation' prop
[- [FE-### | Title]([link])](https://trialtech.atlassian.net/browse/FE-140)
=> added orientation props

apps/web/app/[lang]/blog/page.tsx, apps/web/helpers/category_helpers.ts
Created function to set an arbitrary order to the list of blog categories
[
- [FE-### | Title]([link])](https://trialtech.atlassian.net/browse/FE-142)
=> arbitrary order for blog categories

packages/ui/core/select/Select.tsx
Fix for Category options not taking full width
https://trialtech.atlassian.net/browse/FE-148
=> Select category options not taking full width

apps/web/styles/globals.css
min-height of 320px for WP videos
https://trialtech.atlassian.net/browse/FE-145
=> min-height for videos

apps/web/api/blog/requests.ts, apps/web/app/[lang]/blog/article/[slug]/helpers.ts, apps/web/app/[lang]/blog/components/blogFilter/BlogFilter.tsx, apps/web/models/blog.types.ts
Please include a summary of your changes.
Fixing pagination adding information in getArticle api fetch
- [FE-150| Pagination not working with filter by lang]([https://trialtech.atlassian.net/browse/FE-150])
=> Pagination not working with filter by lang

apps/web/.env.development, apps/web/.env.production, apps/web/app/[lang]/blog/article/[slug]/helpers.ts, apps/web/app/[lang]/blog/article/[slug]/page.tsx, apps/web/middleware.ts
Add HTML Meta Tags to Blog article page
https://trialtech.atlassian.net/browse/FE-163
=> FE-163 Meta Tags Blog post

apps/web/app/robots.ts
Add robots.txt
[Please include a list with the tickets involved in this pull request :pray:
- [FE-### | Title]([link])](https://trialtech.atlassian.net/browse/FE-164)
=> Add robots.txt to disallow crawlers

apps/web/app/[lang]/[...]/page.tsx, apps/web/app/[lang]/blog/article/[slug]/page.tsx, apps/web/app/[lang]/not-found.tsx, apps/web/components/core/layout/footer/Footer.tsx, apps/web/intl/locales/en.json, apps/web/intl/locales/es.json, apps/web/intl/locales/pt.json, packages/ui/core/button/helpers.ts
- Custom not found page
- Button component improves
- Footer layout improves
- [FE-169 | Custom not found page](https://trialtech.atlassian.net/browse/FE-169)
=> FE-169 | Not found page

apps/web/app/[lang]/docs/privacy/page.tsx, apps/web/app/[lang]/docs/terms/page.tsx
- Redirect to not found on documents
- [FE-174 | Create release 0.1.0](https://trialtech.atlassian.net/browse/FE-174)
=> FE-174 | Release 0.1.0

apps/web/api/mocks/FAQs.json
Please include a summary of your changes.
- [FE-### | Title]([link])
=> updated FAQs

apps/web/app/[lang]/about/components/partners/Partners.tsx, apps/web/app/[lang]/about/components/team/Team.tsx
- Change link href
- [FE-178 | Pre release](https://trialtech.atlassian.net/browse/FE-178)
=> FE-178 | Fix typo

apps/web/api/mocks/ourTeam.json
Add new image in ourteam json
- [FE-181| Add new image in ourteam json]([[link](https://trialtech.atlassian.net/browse/FE-181)])
=> adding Martin Jauregui image in ourTeam.json

apps/web/api/mocks/ourTeam.json
{
"image": "https://uepm-dev.sfo3.digitaloceanspaces.com/public/images/jauregui.jpeg",
"name": "Martin Jaureguí Lorda",
"role": "COO",
"about": ""
}
- [FE-182| Change Martin's surname in outeam.json]([[link](https://trialtech.atlassian.net/browse/FE-182)])
=> Change Martin's surname in outeam.json

apps/web/app/[lang]/blog/article/[slug]/styles.css
change style page in order to show list item with the corresponding bullet point
change style page in order to underline a component in paragraph
- [FE-196 | Article detail - Add bullet in li components and undeline a components]([https://trialtech.atlassian.net/browse/FE-196])
=> Article detail - Add bullet in li components and undeline a components

apps/web/components/shared/blogItem/BlogItemContent.tsx, apps/web/components/shared/blogItem/helpers.ts, packages/ui/core/typography/H3.tsx
- Trucate articles title at character 90
- [FE-187 | Wrap blog titles](https://trialtech.atlassian.net/browse/FE-187)
=> FE-186 | Trucate al character 90

apps/web/package.json
- New release 0.1.2
- [FE-177 | Release 0.1.2](https://trialtech.atlassian.net/browse/FE-177)
=> FE-177 | Release 0.1.2

apps/landing-onco/api/useContact.ts, apps/landing-onco/components/contact/ContactForm.tsx, apps/landing-onco/components/contact/contact.type.ts, apps/landing-onco/public/locales/en/translation.json, apps/landing-onco/public/locales/es/translation.json
Allow user to register as doctor or site
- [FE-### | Title]([link])
=> Allow user to register as doctor or site

apps/landing-onco/public/locales/en/translation.json, apps/landing-onco/public/locales/es/translation.json, apps/web/components/shared/contactUs/ContactUsForm.tsx, apps/web/intl/locales/en.json, apps/web/intl/locales/es.json, apps/web/intl/locales/pt.json
Changes in landing-onco texts and protect web Contact Us form with captcha
https://trialtech.atlassian.net/browse/FE-211
=> [HOTFIX] Changes in landing-onco texts and protect web Contact Us form with captcha

apps/web/app/[lang]/maintenance/page.tsx, apps/web/components/core/layout/footer/section/FooterSection.tsx, apps/web/intl/locales/en.json, apps/web/intl/locales/es.json, apps/web/intl/locales/pt.json, apps/web/intl/navigation.ts, apps/web/middleware.ts, apps/web/package.json, yarn.lock
- Maintenance mode
- Vercel edge config 
- [FE-170 | Maintenance mode](https://trialtech.atlassian.net/browse/FE-170)
=> feat: FE-170 | Maintenance mode

apps/web/app/[lang]/layout.tsx, apps/web/components/core/scripts/GTM.tsx
- GTM
- [FE-215 | Add GTM](https://trialtech.atlassian.net/browse/FE-215)
=> hotfix: FE-215 | GTM

apps/web/api/sites/requests.ts, apps/web/app/[lang]/sites/page.tsx
- New /sites api call implemented (to mock all sites)
- sites/page file created and structure implemented (resopnsive mode)
- [FE-197 | Sites page]([[link](https://trialtech.atlassian.net/browse/FE-197)])
=> FE-197 - Sites Page List Structure

packages/ui/components/algolia/map/Clusters.tsx
Improve cluster icon design
- [FE-221| Improve cluster icon design]([(https://trialtech.atlassian.net/browse/FE-221)])
=> FE-221 - Improve cluster icon design

apps/web/app/[lang]/sites/components/browser/SitesBrowser.tsx, apps/web/app/[lang]/sites/components/siteItem/SiteItem.tsx, apps/web/app/[lang]/studies/components/browser/StudiesBrowser.tsx, apps/web/app/[lang]/studies/components/browser/StudiesBrowser.types.ts, apps/web/app/[lang]/studies/components/browser/context/provider.tsx, apps/web/app/[lang]/studies/components/browser/context/reducer.ts, apps/web/app/[lang]/studies/components/browser/context/types.ts, apps/web/app/[lang]/studies/components/browser/index.ts, apps/web/app/[lang]/studies/components/studyItem/StudyItem.tsx, apps/web/app/[lang]/studies/components/studyItem/StudyItem.types.ts, apps/web/app/[lang]/studies/components/studyItem/index.ts, apps/web/app/[lang]/studies/page.tsx, apps/web/intl/navigation.ts, apps/web/models/site.types.ts, apps/web/models/sponsor.types.ts, apps/web/models/study.types.ts
- Studies browser Page layout
- Studies browser context
- Study item layout
- Some code clean up in sites
- [FE-222 | Studies page](https://trialtech.atlassian.net/browse/FE-222)
=> FE-222 | Studies page
